config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  
  root "dashboard#show"
  #root "disc_tests#new"
  resources :questions, only: [:index, :create]
  resources :users, only: [:create, :new]
  resource :session, controller: 'sessions', only: [:create, :new]

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  get 'disc_tests/', to: 'disc_tests#new', as: 'new_disc_test'
  post 'disc_tests/calculate', to: 'disc_tests#calculate_result', as: 'disc_test_calculate_result'

  
  # # Use custom sessions controller for sign-in
  # Custom sign-in route
  get '/login' => 'sessions#new', as: 'signin'
  delete '/logout' => 'sessions#destroy', as: 'signout'
  get '/signup' => 'users#new', as: 'signup'

  # Password Reset
  get 'change_password' => 'users#edit_password', as: :edit_password
  patch 'update_password' => 'users#update_password', as: :update_password


  get 'disc_tests/result/:id', to: 'disc_tests#result', as: 'disc_test_result'
  
  # Catch-all route for unmatched routes
  # match '*path', to: 'application#render_404', via: :all
end

app/controllers/disc_tests_controller.rb
class DiscTestsController < ApplicationController
  def new
  end
  
  def calculate_result
    # Assuming params[:disc_test] contains your test answers
    answers = params[:disc_test] || {}
    dominance_score = answers.values.count('D')
    influence_score = answers.values.count('I')
    steadiness_score = answers.values.count('S')
    compliance_score = answers.values.count('C')
  
    test_result = current_user.disc_test_results.new(
      dominance: dominance_score,
      influence: influence_score,
      steadiness: steadiness_score,
      compliance: compliance_score
    )
  
    if test_result.save
      # Successfully saved the test result
      @dominance = dominance_score
      @influence = influence_score
      @steadiness = steadiness_score
      @compliance = compliance_score
      
      redirect_to disc_test_result_path(id: current_user.disc_test_results.last.id)
    else
      # Handle save failure, e.g., by rendering the form again with error messages
      flash.now[:alert] = "There was a problem saving your test results."
      render :new
    end
  end

  def result
    Rails.logger.debug "DISC Test result action invoked"
    @disc_test_result = current_user.disc_test_results.find(params[:id])

    # Each profile's percentage for the illustration of status bar
    @d_bar = (@disc_test_result.dominance.to_f / 12 * 100).round(2)
    @i_bar = (@disc_test_result.influence.to_f / 12 * 100).round(2)
    @s_bar = (@disc_test_result.steadiness.to_f / 12 * 100).round(2)
    @c_bar = (@disc_test_result.compliance.to_f / 12 * 100).round(2)
    
  rescue ActiveRecord::RecordNotFound
    # Handle the case where the result does not exist or does not belong to the current user
    flash.now[:alert] = "Test result not found."
    redirect_to root_path
  end

  # Here, you can process the answers and calculate the DISC profile
  #@dominance = params[:dominance].to_i
  #@influence = params[:influence].to_i
  # ... capture other attributes similarly

  # Logic to interpret the scores and provide a profile description
  # For example:
  #@profile_description = if @dominance > 7
  #                         "You have a high dominance trait."
  #                       elsif @influence > 7
  #                         "You have a high influence trait."
  #                       end
  # ... and so on
end

app/helpers/disc_tests_helper.rb
module DiscTestsHelper
  #Understanding Strengths and Weaknesses
  def swot_questions
    [
      "Based on my DISC profile, could you identify my key strengths?",
      "Can you highlight some potential weaknesses or areas for improvement based on my DISC traits?"
    ]
  end

  #Communication and Interpersonal Relationships
  def communication_questions
    [
      "How should I adapt my communication to effectively engage with all types of DISC personalities?",
      "What advice can you give me to enhance my relationships, based on my DISC characteristics?"
      ]
  end

  #Teamwork and Collaboration
  def teamwork_questions
    [
      "Given my DISC profile, how can I contribute best to a team setting?",
      "What strategies would you recommend for me to resolve conflicts with team members who have different DISC profiles?"
    ]
  end

  #Leadership and Management
  def leadership_questions
    [
      "What leadership qualities should I focus on developing, considering my DISC profile?",
      "How can I use my DISC insights to manage my team more effectively?"
    ]
  end

  #Adapting to Change  
  def adaptability_questions
    [
      "How can I better handle change and adapt to new situations, according to my DISC traits?",
      "Can you provide some tips on managing stress or uncertainty based on my DISC profile?"
    ]
  end

  #Career Planning
  def career_questions
    [
      "Based on my DISC characteristics, what career paths might be most fulfilling for me?",
      "How can I leverage my DISC traits to advance in my current career or explore new opportunities?"
    ]
  end

  #Personal Growth and Development
  def growth_questions
    [
      "What personal development goals align with my DISC profile strengths and weaknesses?",
      "How can I use my understanding of DISC to enhance my self-awareness and personal growth?"
    ]
  end
end

app/views/disc_tests/_form.html.erb
<%= form_with url: questions_path, method: :post do |f| %>
  <div class="form-group">
    <%= hidden_field_tag :disc_test_result_id, @disc_test_result.id %>
    <%= f.label :question, "Your Question" %>
    <%= f.text_area :question, class: "form-control mb-2", placeholder: "Type your question here..." %>
    
    <%= f.label :predesigned_questions, "Or select a predesigned question:" %>

    <!-- 1st Row Predesigned Questions -->
    <div class="row">
      <!-- SWOT Questions -->
      <div class="col-xl-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#questionsCardSWOT" class="d-block card-header py-3" data-toggle="collapse"
                role="button" aria-expanded="true" aria-controls="questionsCardSWOT">
                <h6 class="m-0 font-weight-bold text-primary">Understanding Strengths and Weaknesses</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse" id="questionsCardSWOT">
                <div class="card-body">
                    <%= f.select :predesigned_questions, options_for_select(swot_questions, selected: nil, disabled: ""), 
                      { prompt: "Choose a question" }, { class: "form-control mb-2", id: "swot_questions" } %>
                </div>
            </div>
        </div>
      </div>

      <!-- Interpersonal Relationship Questions -->
      <div class="col-xl-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#questionsCardCommunication" class="d-block card-header py-3" data-toggle="collapse"
                role="button" aria-expanded="true" aria-controls="questionsCardCommunication">
                <h6 class="m-0 font-weight-bold text-primary">Communication and Interpersonal Relationship</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse" id="questionsCardCommunication">
                <div class="card-body">
                    <%= f.select :predesigned_questions, options_for_select(communication_questions, selected: nil, disabled: ""), 
                      { prompt: "Choose a question" }, { class: "form-control mb-2", id: "communication_questions" } %>
                </div>
            </div>
        </div>
      </div>
    </div>
    <!-- 1st Row Ended -->

    <!-- 2nd Row Predesigned Questions -->
    <div class="row">
      <!-- SWOT Questions -->
      <div class="col-xl-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#questionsCardTeamwork" class="d-block card-header py-3" data-toggle="collapse"
                role="button" aria-expanded="true" aria-controls="questionsCardTeamwork">
                <h6 class="m-0 font-weight-bold text-primary">Teamwork and Collaboration</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse" id="questionsCardTeamwork">
                <div class="card-body">
                    <%= f.select :predesigned_questions, options_for_select(teamwork_questions, selected: nil, disabled: ""), 
                      { prompt: "Choose a question" }, { class: "form-control mb-2", id: "teamwork_questions" } %>
                </div>
            </div>
        </div>
      </div>

      <!-- Interpersonal Relationship Questions -->
      <div class="col-xl-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#questionsCardLeadership" class="d-block card-header py-3" data-toggle="collapse"
                role="button" aria-expanded="true" aria-controls="questionsCardLeadership">
                <h6 class="m-0 font-weight-bold text-primary">Leadership and Management</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse" id="questionsCardLeadership">
                <div class="card-body">
                    <%= f.select :predesigned_questions, options_for_select(leadership_questions, selected: nil, disabled: ""), 
                      { prompt: "Choose a question" }, { class: "form-control mb-2", id: "leadership_questions" } %>
                </div>
            </div>
        </div>
      </div>
    </div>
    <!-- 2nd Row Ended -->

    <!-- 3rd Row Predesigned Questions -->
    <div class="row">
      <!-- SWOT Questions -->
      <div class="col-xl-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#questionsCardAdaptability" class="d-block card-header py-3" data-toggle="collapse"
                role="button" aria-expanded="true" aria-controls="questionsCardAdaptability">
                <h6 class="m-0 font-weight-bold text-primary">Adapting to Change</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse" id="questionsCardAdaptability">
                <div class="card-body">
                    <%= f.select :predesigned_questions, options_for_select(adaptability_questions, selected: nil, disabled: ""), 
                      { prompt: "Choose a question" }, { class: "form-control mb-2", id: "adaptability_questions" } %>
                </div>
            </div>
        </div>
      </div>

      <!-- Interpersonal Relationship Questions -->
      <div class="col-xl-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#questionsCardCareer" class="d-block card-header py-3" data-toggle="collapse"
                role="button" aria-expanded="true" aria-controls="questionsCardCareer">
                <h6 class="m-0 font-weight-bold text-primary">Career Planning</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse" id="questionsCardCareer">
                <div class="card-body">
                    <%= f.select :predesigned_questions, options_for_select(career_questions, selected: nil, disabled: ""), 
                      { prompt: "Choose a question" }, { class: "form-control mb-2", id: "career_questions" } %>
                </div>
            </div>
        </div>
      </div>
    </div>
    <!-- 3rd Row Ended -->

    <!-- 4th Row Predesigned Questions -->
    <div class="row">
      <!-- SWOT Questions -->
      <div class="col-xl-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <a href="#questionsCardGrowth" class="d-block card-header py-3" data-toggle="collapse"
                role="button" aria-expanded="true" aria-controls="questionsCardGrowth">
                <h6 class="m-0 font-weight-bold text-primary">Personal Growth and Development</h6>
            </a>
            <!-- Card Content - Collapse -->
            <div class="collapse" id="questionsCardGrowth">
                <div class="card-body">
                    <%= f.select :predesigned_questions, options_for_select(growth_questions, selected: nil, disabled: ""), 
                      { prompt: "Choose a question" }, { class: "form-control mb-2", id: "growth_questions" } %>
                </div>
            </div>
        </div>
      </div>
    </div>
    <!-- 4th Row Ended -->
    
    
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/disc_tests/new.html.erb
<div class="row">
    <div class="col-xl-12 col-lg-7">
        <div class="card shadow mb-4">
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">DISC Test</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
              <%= form_tag disc_test_calculate_result_path, method: :post, class: "bg-light p-5 rounded", data: { turbo: "false" } do %>
                <div class="form-group">
                  <label>Question 1: When faced with a decision, I prefer to:</label><br>
                  <%= radio_button_tag 'disc_test[question_1]', 'D', required: true %> Quickly make a choice and take action.<br>
                  <%= radio_button_tag 'disc_test[question_1]', 'I' %> Discuss it with others and gather opinions.<br>
                  <%= radio_button_tag 'disc_test[question_1]', 'S' %> Take my time to think it through.<br>
                  <%= radio_button_tag 'disc_test[question_1]', 'C' %> Analyze all the data and details first.<br>
                </div>

                <div class="form-group">
                  <label>Question 2: In a team setting, I am:</label><br>
                  <%= radio_button_tag 'disc_test[question_2]', 'D', required: true %> Often the leader or the one who sets the direction.<br>
                  <%= radio_button_tag 'disc_test[question_2]', 'I' %> The motivator who keeps the energy up.<br>
                  <%= radio_button_tag 'disc_test[question_2]', 'S' %> The reliable one who ensures tasks get done.<br>
                  <%= radio_button_tag 'disc_test[question_2]', 'C' %> The detail-oriented one who checks for accuracy.<br>
                </div>

                <div class="form-group">
                  <label>Question 3: I feel most accomplished when:</label><br>
                  <%= radio_button_tag 'disc_test[question_3]', 'D', required: true %> I achieve my goals.<br>
                  <%= radio_button_tag 'disc_test[question_3]', 'I' %> I inspire or help others.<br>
                  <%= radio_button_tag 'disc_test[question_3]', 'S' %> I maintain harmony in the group.<br>
                  <%= radio_button_tag 'disc_test[question_3]', 'C' %> I ensure everything is accurate and correct.<br>
                </div>
                
                <div class="form-group">
                  <label>Question 4: I describe myself as:</label><br>
                  <%= radio_button_tag 'disc_test[question_4]', 'D', required: true %> Direct and daring.<br>
                  <%= radio_button_tag 'disc_test[question_4]', 'I' %> Social and spirited.<br>
                  <%= radio_button_tag 'disc_test[question_4]', 'S' %> Calm and consistent.<br>
                  <%= radio_button_tag 'disc_test[question_4]', 'C' %> Precise and perfectionistic.<br>
                </div>

                <div class="form-group">
                  <label>Question 5: In a disagreement, I tend to:</label><br>
                  <%= radio_button_tag 'disc_test[question_5]', 'D', required: true %> Stand my ground and debate my point.<br>
                  <%= radio_button_tag 'disc_test[question_5]', 'I' %> Try to persuade others with enthusiasm.<br>
                  <%= radio_button_tag 'disc_test[question_5]', 'S' %> Listen and seek compromise.<br>
                  <%= radio_button_tag 'disc_test[question_5]', 'C' %> Rely on facts and data to make my point.<br>
                </div>

                <div class="form-group">
                  <label>Question 6: I value:</label><br>
                  <%= radio_button_tag 'disc_test[question_6]', 'D', required: true %> Results and achievements.<br>
                  <%= radio_button_tag 'disc_test[question_6]', 'I' %> Interactions and relationships.<br>
                  <%= radio_button_tag 'disc_test[question_6]', 'S' %> Stability and reliability.<br>
                  <%= radio_button_tag 'disc_test[question_6]', 'C' %> Accuracy and thoroughness.<br>
                </div>

                <div class="form-group">
                  <label>Question 7: When starting a new project, I:</label><br>
                  <%= radio_button_tag 'disc_test[question_7]', 'D', required: true %> Jump right in and set the goals.<br>
                  <%= radio_button_tag 'disc_test[question_7]', 'I' %> Share my excitement with others.<br>
                  <%= radio_button_tag 'disc_test[question_7]', 'S' %> Plan carefully and set a steady pace.<br>
                  <%= radio_button_tag 'disc_test[question_7]', 'C' %> Gather all the necessary information first.<br>
                </div>

                <div class="form-group">
                  <label>Question 8: I am often praised for my:</label><br>
                  <%= radio_button_tag 'disc_test[question_8]', 'D', required: true %> Leadership skills.<br>
                  <%= radio_button_tag 'disc_test[question_8]', 'I' %> Ability to energize and motivate others.<br>
                  <%= radio_button_tag 'disc_test[question_8]', 'S' %> Patience and consistency.<br>
                  <%= radio_button_tag 'disc_test[question_8]', 'C' %> Attention to detail.<br>
                </div>

                <div class="form-group">
                  <label>Question 9: In a group, I'd rather be:</label><br>
                  <%= radio_button_tag 'disc_test[question_9]', 'D', required: true %> Setting the direction.<br>
                  <%= radio_button_tag 'disc_test[question_9]', 'I' %> Building relationships.<br>
                  <%= radio_button_tag 'disc_test[question_9]', 'S' %> Supporting others.<br>
                  <%= radio_button_tag 'disc_test[question_9]', 'C' %> Ensuring accuracy.<br>
                </div>

                <div class="form-group">
                  <label>Question 10: When learning something new, I:</label><br>
                  <%= radio_button_tag 'disc_test[question_10]', 'D', required: true %> Dive in and learn by doing.<br>
                  <%= radio_button_tag 'disc_test[question_10]', 'I' %> Discuss it with others and share ideas.<br>
                  <%= radio_button_tag 'disc_test[question_10]', 'S' %> Take a systematic approach.<br>
                  <%= radio_button_tag 'disc_test[question_10]', 'C' %> Focus on the details and the process.<br>
                </div>

                <div class="form-group">
                  <label>Question 11: I handle change by:</label><br>
                  <%= radio_button_tag 'disc_test[question_11]', 'D', required: true %> Seeing it as a new challenge to conquer.<br>
                  <%= radio_button_tag 'disc_test[question_11]', 'I' %> Embracing it with optimism.<br>
                  <%= radio_button_tag 'disc_test[question_11]', 'S' %> Adapting slowly and methodically.<br>
                  <%= radio_button_tag 'disc_test[question_11]', 'C' %> Analyzing the implications and details.<br>
                </div>

                <div class="form-group">
                  <label>Question 12: My approach to tasks is:</label><br>
                  <%= radio_button_tag 'disc_test[question_12]', 'D', required: true %> Goal-oriented and fast-paced.<br>
                  <%= radio_button_tag 'disc_test[question_12]', 'I' %> Collaborative and enthusiastic.<br>
                  <%= radio_button_tag 'disc_test[question_12]', 'S' %> Steady and methodical.<br>
                  <%= radio_button_tag 'disc_test[question_12]', 'C' %> Systematic and detail-oriented.<br>
                </div>

                <%= submit_tag "Submit", class: "btn btn-primary" %>
              <% end %>
            </div>
        </div>
    </div>
</div>

app/views/disc_tests/result.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">DISC Profile</h1>
    <%# <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> %>
</div>

<!-- Profile Illustration Row -->

<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-12 col-lg-7">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Personality Profiles Analysis</h6>
            </div>
            <div class="card-body">
                <h4 class="small font-weight-bold">Dominance <span
                        class="float-right"><%=@d_bar%>%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-danger" role="progressbar" style="width: <%=@d_bar%>%"></div>
                </div>
                <h4 class="small font-weight-bold">Influence <span
                        class="float-right"><%=@i_bar%>%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-warning" role="progressbar" style="width: <%=@i_bar%>%"></div>
                </div>
                <h4 class="small font-weight-bold">Steadiness <span
                        class="float-right"><%=@s_bar%>%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-success" role="progressbar" style="width: <%=@s_bar%>%"></div>
                </div>
                <h4 class="small font-weight-bold">Compliance <span
                        class="float-right"><%=@c_bar%>%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar" role="progressbar" style="width: <%=@c_bar%>%"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<%#= turbo_frame_tag "new_question", target: "_top" do %>
  <%#= form_tag questions_path, class: 'w-full' do |f| %>
    <%# <input type="text"
            class="w-full rounded"
            name="question[question]"
            placeholder="Type your question"> %>
  <%# end %>
<%# end %>

<%# <div class="h-48 w-full rounded mb-5 p-3 bg-gray-100"> %>
  <%#= turbo_frame_tag "answer" %>
<%# </div> %>

<div class="row">
  <div class="col-xl-12 col-lg-7 col-md-6">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Personality Profiles Analysis</h6>
      </div>

      <div class="card-body">
        <%= render partial: '/disc_tests/form' %>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const questionSwotSelect = document.getElementById('swot_questions');
    const questionCommunicationSelect = document.getElementById('communication_questions');
    const questionTeamworkSelect = document.getElementById('teamwork_questions');
    const questionLeadershipSelect = document.getElementById('leadership_questions');
    const questionAdaptabilitySelect = document.getElementById('adaptability_questions');
    const questionCareerSelect = document.getElementById('career_questions');
    const questionGrowthSelect = document.getElementById('growth_questions');
    const questionForm = document.getElementById('question_form');
    const questionInput = document.getElementById('question');

    questionSwotSelect.addEventListener('change', function() {
      questionInput.value = this.value; // Set the text area to the selected question
    });

    questionCommunicationSelect.addEventListener('change', function() {
      questionInput.value = this.value; // Set the text area to the selected question
    });

    questionTeamworkSelect.addEventListener('change', function() {
      questionInput.value = this.value; // Set the text area to the selected question
    });

    questionLeadershipSelect.addEventListener('change', function() {
      questionInput.value = this.value; // Set the text area to the selected question
    });

    questionAdaptabilitySelect.addEventListener('change', function() {
      questionInput.value = this.value; // Set the text area to the selected question
    });

    questionCareerSelect.addEventListener('change', function() {
      questionInput.value = this.value; // Set the text area to the selected question
    });

    questionGrowthSelect.addEventListener('change', function() {
      questionInput.value = this.value; // Set the text area to the selected question
    });

    // Submit form immediately upon selecting a question:
    // questionSelect.addEventListener('change', function() {
    //   questionForm.submit();
    // });
  });
</script>

<%# <script>
  document.addEventListener('DOMContentLoaded', function() {
    const questionButtons = document.querySelectorAll('.question-btn');
    // Use getElementById to select the textarea by its ID
    const questionInput = document.getElementById('question');

    questionButtons.forEach(button => {
      button.addEventListener('click', function(event) {
        event.preventDefault(); // Prevent the default button action
        questionInput.value = this.getAttribute('data-question');
      });
    });
  });
</script> %>

<div class="row">
  <div class="col-xl-12 col-lg-7">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Answer</h6>
      </div>
      <div class="card-body">
        <%= turbo_frame_tag "answer" do %>
          <!-- This is where the answer will be displayed. -->
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/disc_tests/show.html.erb
<h1>Your DISC Profile</h1>

<p>Dominance: <%= @disc_response.dominance %></p>
<p>Influence: <%= @disc_response.influence %></p>
<!-- Display other attributes similarly -->

<!-- You can add logic here to interpret the scores and provide a more detailed profile description -->