config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  
  root "dashboard#show"
  #root "disc_tests#new"
  resources :questions, only: [:index, :create]
  resources :users, only: [:create, :new]
  resource :session, controller: 'sessions', only: [:create, :new]

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  get 'disc_tests/', to: 'disc_tests#new', as: 'new_disc_test'
  post 'disc_tests/calculate', to: 'disc_tests#calculate_result', as: 'disc_test_calculate_result'

  
  # # Use custom sessions controller for sign-in
  # Custom sign-in route
  get '/login' => 'sessions#new', as: 'signin'
  delete '/logout' => 'sessions#destroy', as: 'signout'
  get '/signup' => 'users#new', as: 'signup'

  # Password Reset
  get 'change_password' => 'users#edit_password', as: :edit_password
  patch 'update_password' => 'users#update_password', as: :update_password


  get 'disc_tests/result/:id', to: 'disc_tests#result', as: 'disc_test_result'
  
  # Catch-all route for unmatched routes
  # match '*path', to: 'application#render_404', via: :all
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :disc_test_results
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def new
    @user = User.new
    render layout: false
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Account created successfully. Please log in."
      redirect_to signin_path
    else
      flash.now[:error] = "There was an error creating your account."
      render :new, layout: false
    end
  end

  def edit_password
    # Renders the form
  end

  def update_password
    user = current_user
    if current_user.authenticated?(params[:current_password])
      if current_user.update(password: params[:new_password], password_confirmation: params[:new_password_confirmation])
        flash[:notice] = 'Password was successfully updated.'
        redirect_to profile_path # or wherever you wish
      else
        flash.now[:alert] = 'There was a problem updating your password.'
        render :edit_password
      end
    else
      flash.now[:alert] = 'Current password is incorrect.'
      render :edit_password
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-group">
  <%= form.email_field :email, class: "form-control form-control-user", placeholder: "Email Address" %>
</div>

<div class="form-group">
  <%= form.password_field :password, class: "form-control form-control-user", placeholder: "Password" %>
</div>

app/views/users/edit_password.html.erb
<% flash.each do |message_type, message| %>
    <% byebug %>
    <div class="alert alert-<%= message_type == 'notice' ? 'success' : 'danger' %>" role="alert">
    <%= message %>
    </div>
<% end %>
<h2>Change Password</h2>
<h2><%= flash[:alert] %></h2>

<%= form_for :user, url: update_password_path, html: { method: :patch } do |f| %>
  <div class="field">
    <%= f.label :current_password %><br>
    <%= f.password_field :current_password, required: true %>
  </div>

  <div class="field">
    <%= f.label :new_password, "New Password" %><br>
    <%= f.password_field :new_password, required: true %>
  </div>

  <div class="field">
    <%= f.label :new_password_confirmation, "Confirm New Password" %><br>
    <%= f.password_field :new_password_confirmation, required: true %>
  </div>

  <div class="actions">
    <%= f.submit "Change Password" %>
  </div>

<% end %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AI DISC Consultant</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.css" rel="stylesheet">
</head>

<body class="bg-gradient-primary">

    <div class="container">
        <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-6">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Account Registration</h1>
                            </div>

                            <% if @user.errors.any? %>
                            <div class="alert alert-danger" role="alert">
                                <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:

                                <ul>
                                <% @user.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                <% end %>
                                </ul>
                            </div>
                            <% end %>
                            
                            <%= form_for @user, html: { class: "user" } do |form| %>
                                <%= render partial: '/users/form', object: form %>

                                <!--<div class="submit-field">-->
                                <%= form.submit class: "btn btn-primary btn-user btn-block" %>
                                <!--</div>-->

                                <!--<div class="other-links">-->
                                <%#= link_to t(".sign_in"), signin_path %>
                                <!--</div>-->
                            <% end %>

                            <hr>
                            <div class="text-center">
                                <a class="small" href="/login">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>